### ISSUE TITLE
If a complete SQL statement is put in msg.topic and msg.payload is empty, an error occurs.

### ISSUE THREAD

**Issue by juggledad** [stackhero-io/node-red-contrib-stackhero-mysql#1]
If I put "select * from foo" into msg.topic (where 'foo' is an actual table) and msg.payload is empty, an error is returned with the message:

> "msg.payload should be an object containing the query arguments."

The seems like a bug since there are no query arguments in this query.

**Comment by Bacto** [comment]
Hi,

Thanks for this issue.
This is resolved with 1.0.3 :)
