### ISSUE TITLE
Node is showing Error:Pool is closed

### ISSUE THREAD

**Issue by cdevereu** [stackhero-io/node-red-contrib-stackhero-mysql#4]
I'm using this node within the latest node-red version to connect to a Stackhero MariaDB and the node is showing this error message underneath.  The connection to the DB appears to work still, and still allows me to query the DB it seems.  Any ideas what might be causing this, it's bothering me!

**Comment by geekgarage** [comment]
@cdevereu you didn't post the actual error :)

**Comment by cdevereu** [comment]
@geekgarage That's the thing, there wasn't anything else other than the what appeared under the node on the canvas.  Nothing in the debug window.  I've since restarted node-red and the error hasn't re-occurred.  Happy to close this and re-post if it happens again.

**Comment by Bacto** [comment]
Hi,

It is possible that this error is show because the node can't connect to your MySQL server.
Each 5 seconds the node tries to connect again, so if your server is coming back, the error should disappear automatically.

I close the issue as it seems you can't reproduce it.

**Comment by cdevereu** [comment]
That's a fair assumption @Bacto although the MySQL server is running on Stackhero :)

**Comment by geekgarage** [comment]
@cdevereu i think i found the cause to you issue (realised after i posted it) try have a look in the https://github.com/stackhero-io/node-red-contrib-stackhero-mysql/issues/8
