### ISSUE TITLE
1.0.3 : breaking change

### ISSUE THREAD

**Issue by 0rsa** [stackhero-io/node-red-contrib-stackhero-mysql#6]
Upgrading to the latest 1.0.3, all my queries return now : "msg.payload should be an object containing the query arguments."
msg.payload is correct and was working fine before update.
I roll back to previous version.

"msg.payload should be an object containing the query arguments."

topic: "INSERT IGNORE INTO enedis VALUES(:id, :instant, :base);"
payload: object
   id: "2021-01-23 07:53:24"
   instant: "13"
   base: "017387265"

**Comment by GrimbiXcode** [comment]
I have already opened a pull request for this: https://github.com/stackhero-io/node-red-contrib-stackhero-mysql/pull/3

**Comment by Bacto** [comment]
Hi @0rsa and @GrimbiXcode,
Can you give me an example of payload that is rejected? I don't understand why it doesn't work with the current code.

**Comment by Bacto** [comment]
Got it. It didn't work with `Object.create(null)`.
It is resolved with 1.0.4.
Thanks to you two :)

**Comment by GrimbiXcode** [comment]
Nice, thanks!
